.\" Manual Page for gde2-system-monitor
.TH GDE2-SYSTEM-MONITOR 1 "10 February 2014" "GDE2 Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME" 
gde2-system-monitor \- view and control processes 
.SH "SYNOPSIS" 
.PP 
.B gde2-system-monitor [OPTIONS]  
.SH "DESCRIPTION" 
.PP 
The \fBgde2-system-monitor\fR allows you to view and control the processes running on your system. You can access detailed memory maps, send signals, and terminate the processes. 
.PP 
In addition, the \fBgde2-system-monitor\fR provides an overall view of the resource usage on your system, including memory and CPU allocation, as well as network usage. It also allows you to view file system information such as Device, Type, Mountpoints, and Disk Usage.
.PP
The System tab will display basic information about your system like Hostname, Kernel, GDE2 Version, Installed Memory, and Processor Information.
.SH "OPTIONS" 
This program accepts all the standard GDE2 and GTK+ options, which follow the usual GNU command line syntax, with long options starting with two dashes ('\-').  In addition to those standard GDE2 options, the gde2-system-monitor accepts the following options: 
.TP
\fB\-s, \-\-show\-system\-tab\fR
Show the System tab. 
.TP
\fB\-?, \-h, \-\-help\fR
Print standard command line options.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/gde2-desktop/gde2-system-monitor/issues
.SH "AUTHORS" 
.SS The GDE2 System Monitor (gde2\-system\-monitor) is maintained by The GDE2 developers:
.nf
Perberos <perberos@gmail.com>
Stefano Karapetsas <stefano@karapetsas.com>
Steve Zesch <stevezesch2@gmail.com>
.fi
.SS This Man Page has been updated/re-written for the GDE2 Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "HISTORY"
.SS The gnome-system-monitor was written by:
Kevin Vandersloot, Erik Johnsson, Jorgen Scheibengruber, Benoît Dejean, Paolo Borelli & Karl Lattimer.
.SS This manual page was originally written by Colin Walters <walters@debian.org> for the Debian system. 
.SH "LICENSE"
Permission is granted to copy, distribute and/or modify this document under the terms of the \fBGNU Free Documentation License, Version 1.1\fR or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts and no Back-Cover Texts. 
.SH "SEE ALSO"
.SS
GDE2 System Monitor documentation can be found from the "Help" menu, or by pressing the F1 key. 
Further information may also be available at: http://wiki.gde2-desktop.org/docs
